### ISSUE TITLE
Review ecs193-final-report

### ISSUE THREAD

**Issue by lxylxy123456** [LibreTexts/ngshare#119]
I merged `user-guide` and `master`, and the new branch is now `ecs193-final-report`. If everything is fine we can then remove `user-guide` branch. 

https://ngshare.readthedocs.io/en/ecs193-final-report/index.html

**Comment by rkevin-arch** [comment]
I'm OK with this.

**Comment by Lawrence37** [comment]
Looks good.

**Comment by lxylxy123456** [comment]
@aalmanza1998 You can close this issue if you have completed your review.
