### ISSUE TITLE
ngshare v0.5.2 deployment specification error

### ISSUE THREAD

**Issue by simon-ball** [LibreTexts/ngshare#130]
Configuration:
* Docker desktop 2.3.0.4, kubernetes v1.16.5
* Running on Windows 10 Education 1809.
* Following the install guide in https://github.com/LibreTexts/ngshare/tree/master/testing/install_z2jh, albeit running in Powershell rather than Bash

I don't have easy access to a Linux host running Kubernetes right now, so I can't test if this is purely a problem with trying to run on a Windows host. 

With _any_ of the v0.5.2 entries in https://LibreTexts.github.io/ngshare-helm-repo/index.yaml, , attempting to run the following command:
`helm install ngshare ngshare/ngshare -f config_ngshare.yaml -n <namespace>` _or_ `helm install ngshare ngshare/ngshare -f config_ngshare.yaml -n <namespace> --version 0.5.2` results in the following error:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.strategy): invalid type for io.k8s.api.apps.v1.DeploymentStrategy: got "string", expected "map"  `

Instead, pointing at a previous version, ngshare is deployed successfully (where "successfully" means displaying the success message
`helm install ngshare ngshare/ngshare -f config_ngshare.yaml -n <namespace> --version 0.5.1`
```
NOTES:
Congrats, ngshare should be installed! To get started... <snip>
```

My best guess is that this relates to the changes made in commit 23c5c72afd53739e421fb63a0e5fb529a31ba57a ("Expose deployment strategy")

**Comment by rkevin-arch** [comment]
This should now be fixed in 0.5.3..
