### ISSUE TITLE
ngshare Pends Forever?

### ISSUE THREAD

**Issue by mdweisner** [LibreTexts/ngshare#133]
Hello! We have been trying to implement ngshare for courses using Zero to Jupyterhub with Kubernetes on the Google Cloud Platform this Fall. It seems like a great tool but we've run into a few snags I'm hoping you can help with.

Installation appeared to go okay, but when I go to the ngshare service in my Google Cloud Platform hosted Jupyterhub interface, I get this error:

503 : Service Unavailable
Your server appears to be down. Try restarting it from the hub

Checking the pods, it appears that the ngshare pod was listed as pending eternally. Checking the kubernetes logs, it seems that it may be due to the fact that we are using a user pool and it can't tolerate the tainted user pool, perhaps?

I see a few potential areas for confusion based on the documentation:

1) we use an already published docker image (rather than creating a docker file locally). I think this is an issue as we can't easily update the nbgrader_config.py after it sets up the api calls.

2) As mentioned, we use a dedicated user pool for scaling. This seems like a likely culprit, as the ngshare pod may not be able to tolerate the nodepool. Could this be the issue?

3) I get a bit confused between the primary documentation and the example installation.

We are not using minikube, as referenced in the z2jh installation example, but instead creating a cluster and a dedicated scaling user pool. 

I noticed that in the [installation example](https://github.com/LibreTexts/ngshare/tree/master/testing/install_z2jh) you use a separate config_ngshare.yaml file. What I find a little confusing is that you do not include this in your [installation instructions.](https://ngshare.readthedocs.io/en/latest/user_guide/install_z2jh.html).

There are a few discrepencies that I'm having trouble navigating between the namespace, the api url, and updating the image.  Sorry this is a bit all over the place but if you can help me wade through the issues I'd appreciate it, thanks!

Best,
Michael Weisner

**Comment by rkevin-arch** [comment]
Hi!

I'm not entirely familiar with what a user pool is, so I'll have to look into that. What does `kubectl describe` say when you run it on the ngshare pod?

Also, for the installation instructions, there are a couple of `config.yaml` examples in there listed near the top, under the [Installing the Helm chart](https://ngshare.readthedocs.io/en/latest/user_guide/install_z2jh.html#installing-the-helm-chart) section. That said, even if you don't have such a `config.yaml` it should've still autogenerated a token and should still function. I'll look into the user pool issue.

**Comment by rkevin-arch** [comment]
I can't find any information on "kubernetes user pools". Do you have any documentation you can link to to help me understand them?

**Comment by mdweisner** [comment]
Hi! Thanks for getting back to me!

Sorry if my terminology is a little confusing, but it's how it's referred to in the [Zero to JupyterHub documentation ](https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html?highlight=user%20pool) (scroll down to the bottom). Basically you set up a pool of autoscaling nodes for the users to utilize and taint them so that users logging in get scheduled onto those nodes, rather than any nodes designated for other use.

kubectl describe returned this:

Name:           ngshare-fall-jhub-ngshare-6b7b864d7b-wflnn
Namespace:      fall-jhub-ngshare
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=ngshare-fall-jhub-ngshare
                app.kubernetes.io/name=ngshare
                pod-template-hash=6b7b864d7b
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/ngshare-fall-jhub-ngshare-6b7b864d7b
Containers:
  ngshare:
    Image:      libretexts/ngshare:v0.5.3
    Port:       8080/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:http/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      JUPYTERHUB_SERVICE_NAME:    ngshare
      JUPYTERHUB_API_TOKEN:       <set to the key 'token' in secret 'ngshare-token'>  Optional: false
      JUPYTERHUB_API_URL:         http://hub:8081/hub/api
      JUPYTERHUB_BASE_URL:        /
      JUPYTERHUB_SERVICE_PREFIX:  /services/ngshare/
      JUPYTERHUB_SERVICE_URL:     http://0.0.0.0:8080/
    Mounts:
      /srv/ngshare from ngshare-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jglpm (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  ngshare-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ngshare-pvc
    ReadOnly:   false
  default-token-jglpm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jglpm
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Normal   NotTriggerScaleUp  63s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had taints that the pod didn't 
tolerate
  Warning  FailedScheduling   41s (x3 over 65s)  default-scheduler   pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

And thanks for that link but I do have a config.yaml, the thing that's a little confusing is that the [installation example here](https://github.com/LibreTexts/ngshare/tree/master/testing/install_z2jh) has two configs, but it's not referred that way in the link you sent so I'm unsure how that config.yaml relates.

Thanks again!

**Comment by mdweisner** [comment]
I should maybe also mention that I get warnings that "[Warning] pod has unbound immediate PersistentVolumeClaims"

Which I presume is because the ngshare pod isn't running and thus can't properly make the claims?

**Comment by rkevin-arch** [comment]
The `pod has unbound immediate PersistentVolumeClaims` issue is the problem here, since ngshare needs a piece of persistent storage to store its database. Do you have a persistent volume provisioner set up correctly? How are Z2JH's persistent volume claims satisfied?

**Comment by mdweisner** [comment]
ah great, that is something I'm unsure about. 

The [documentation for installation](https://ngshare.readthedocs.io/en/latest/user_guide/install_z2jh.html) says that it "assumes you already have a Kubernetes cluster with a persistent volume provisioner (which should be the case if you run Z2JH)." 

I've followed the Zero to JupyterHub path already but it doesn't really seem to address PVCs following the basic steps, so I must be missing something there.

Would this section satisfy that potentially?

https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-storage.html#google-cloud

Thanks again!

**Comment by rkevin-arch** [comment]
I think I know what's going on. Can you test by putting this in the ngshare's `config.yaml`?
```yaml
pvc:
  accessModes:
  - ReadWriteOnce
```

**Comment by mdweisner** [comment]
Will do and will build from scratch again to make sure nothing is interfering!

**Comment by rkevin-arch** [comment]
I think the issue is that in the helm chart, the PVC has access mode `ReadWriteMany`, and GCEPersistentDisk volumes do not support that.

There really isn't a strong reason why we need to mount it `ReadWriteMany` instead of `ReadWriteOnce` (once upon a time we discussed running multiple ngshare instances at once but gave up on that idea, this is probably a remnant from that). We're probably gonna change it to be `ReadWriteOnce` by default, but setting it explicitly like this is a good idea in the meantime.

Also, I see you're having some issues with running ngshare in a separate namespace. If you install it in the same namespace as Z2JH, it should just work out of the box, so I'd recommend that. If you really want to install it in a separate namespace, let me know and I can explain the documentation.

**Comment by mdweisner** [comment]
So the good news is that it no longer pends! But unfortunately it's still not working 100%.

I ran kubectl describe on it and got these events:

Events:
  Type     Reason                  Age                    From                                                       Message
  ----     ------                  ----                   ----                                                       -------
  Warning  FailedScheduling        2m27s (x2 over 2m30s)  default-scheduler                                          pod has unbound immediate PersistentVolumeClaims (repeated 2 ti
mes)
  Normal   NotTriggerScaleUp       2m27s                  cluster-autoscaler                                         pod didn't trigger scale-up (it wouldn't fit if a new node is a
dded): 1 node(s) had taints that the pod didn't tolerate
  Normal   Scheduled               2m25s                  default-scheduler                                          Successfully assigned fall-jhub-ngshare/ngshare-fall-jhub-ngsha
re-6b7b864d7b-qlhcq to gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt
  Normal   SuccessfulAttachVolume  2m19s                  attachdetach-controller                                    AttachVolume.Attach succeeded for volume "pvc-ad71382e-1e67-42e
4-b1ae-12b4a6ecb9e8"
  Normal   Pulling                 2m9s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Pulling image "libretexts/ngshare:v0.5.3"
  Normal   Pulled                  2m2s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Successfully pulled image "libretexts/ngshare:v0.5.3"
  Normal   Created                 119s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Created container ngshare
  Normal   Started                 119s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Started container ngshare
  Warning  Unhealthy               116s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Readiness probe failed: Get http://10.0.1.10:8080/healthz: dial
 tcp 10.0.1.10:8080: connect: connection refused
  Warning  Unhealthy               116s                   kubelet, gke-fall-jhub-ngshare-default-pool-8ea280cd-2bnt  Liveness probe failed: Get http://10.0.1.10:8080/healthz: dial 
tcp 10.0.1.10:8080: connect: connection refused

**Comment by mdweisner** [comment]
And looking at the ngshare service returns "500: Internal Server Error"

**Comment by rkevin-arch** [comment]
Can you do a `kubectl logs -n fall-jhub-ngshare ngshare-fall-jhub-ngshare-6b7b864d7b-wflnn`? (or whatever the pod name is now)

**Comment by rkevin-arch** [comment]
Oh wait, I think I know why, since it's in a different namespace. What is your Z2JH namespace?

**Comment by rkevin-arch** [comment]
Add this to your ngshare `config.yaml`:
```yaml
ngshare:
  hub_api_url: http://hub.your-z2jh-namespace.svc.cluster.local:8081/hub/api
```
replacing `your-z2jh-namespace` with the namespace.
Afterwards, you have to change your `nbgrader_config.py` that you put in your singleuser image based on the new helm output.

**Comment by mdweisner** [comment]
Hi, sure thing but it appears that it's now working thanks to your suggestions! When I go to the ngshare service I now get the "Hello, world! from ngshare" greeting!

It is in a namespace, yes, I've been doing everything in the fall-jhub-ngshare namespace. It's a bit messy with the naming.

Here's the full logs from the ngshare pod:

$ kubectl logs ngshare-fall-jhub-ngshare-6b7b864d7b-qlhcq --namespace $NAMESPACE
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> aa00db20c10a, Init
INFO  [alembic.runtime.migration] Running upgrade aa00db20c10a -> 1921a169739b, Add file size

I actually already did change the namespace you mentioned, the tricky part was that I actually have to do it in advance because I am not building it locally, but rather pushing to dockerhub (kind of convoluted), but it seems to be working!

Thanks so much for your help, Kevin! I really appreciate it and am excited to get going with ngshare this semester!

**Comment by rkevin-arch** [comment]
No problem! Hopefully it works properly. If not, feel free to open an issue here at any time.

**Comment by alpha-nome** [comment]
Hello. I have the same issue with AKS. 

 Warning  FailedScheduling   4m48s  default-scheduler   0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling   4m48s  default-scheduler   0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling   2m10s  default-scheduler   0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   NotTriggerScaleUp  4m41s  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 pod has unbound immediate PersistentVolumeClaims

I think some issue with PVC. Not sure how to resolve this.

**Comment by alpha-nome** [comment]
Hello. I'm deploying ngshare in the same namespace as hub. But still I'm facing the readiness probe: failed issue.

Here is the output of my describe pod command: The pod shows running. I'm using Azure Kubernetes service

Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Warning  FailedScheduling        3m18s  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        3m18s  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               3m16s  default-scheduler        Successfully assigned dev/ngshare-67d7587685-bmnht to aks-nodepool1-16227594-vmss000005
  Normal   SuccessfulAttachVolume  2m56s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8dd1e83a-c2b6-48d7-8364-de80e316ed69"
  Normal   Pulled                  2m43s  kubelet                  Container image "libretexts/ngshare:v0.5.3" already present on machine
  Normal   Created                 2m43s  kubelet                  Created container ngshare
  Normal   Started                 2m43s  kubelet                  Started container ngshare
  Warning  Unhealthy               2m43s  kubelet                  Readiness probe failed: Get "http://10.240.0.40:8080/healthz": dial tcp 10.240.0.40:8080: connect: connection refused
