### ISSUE TITLE
ngshare blocks and restarts when accessed

### ISSUE THREAD

**Issue by BenGig** [LibreTexts/ngshare#139]
I try to deploy ngshare in a k8s (on premise). As far as I can see, ngshare is running and is accessible. The health check

`curl http://localhost:8080/healthz`

works, and I can see the Services/ngshare menu entry in the hub control panel. But I encounter issues when accessing ngshare. When I try to open the ngshare page, the ngshare server seems to lock up, the k8s health check eventually fails, and the container restarts, resulting in a 503 error. I see the same behavior when I enter a Jupyter notebook and issue a command `ngshare-course-management create_course test`.

When I try accessing ngshare with a command like

`wget --header="Authorization: token <TOKEN>" -S http://ngshare-devel.jhub-devel.svc.cluster.local:8080/api/`

For any api URL other than the health check, I always get this response

```
<h1>404 Not Found</h1>
{
 "DEBIAN_FRONTEND": "noninteractive",
 "HOME": "/",
 "HOSTNAME": "ngshare-devel-67cccf5b44-jgmwd",
...
```

I tried to start ngshare with the --debug option, but I see no information which could guide me through the debug process, I'm stuck. How do I get more information about what's going wrong?

**Comment by rkevin-arch** [comment]
Thanks for the bug report! Can you try upgrading the helm chart version to `0.5.3-n008.h44632c7` and see if it fixes the issue?

**Comment by BenGig** [comment]
Great work! Your release fixed the issue, thanks.
