### ISSUE TITLE
Readiness probe failed on deploying in same namespace

### ISSUE THREAD

**Issue by alpha-nome** [LibreTexts/ngshare#143]
Hi,

I've deployed ngshare in the namespace as my hub. And configured the hub_uri as per the documentation. I'm getting 503 error on ngserve in services. 

This is the output of my describe pods command

Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Warning  FailedScheduling        2m16s  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        2m16s  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               2m13s  default-scheduler        Successfully assigned dev/ngshare-67d7587685-r85kd to aks-nodepool1-16227594-vmss000005
  Normal   SuccessfulAttachVolume  103s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-02c1c098-c0a6-4cda-b348-788e8ff1343f"
  Normal   Pulled                  101s   kubelet                  Container image "libretexts/ngshare:v0.5.3" already present on machine
  Normal   Created                 100s   kubelet                  Created container ngshare
  Normal   Started                 100s   kubelet                  Started container ngshare
  Warning  Unhealthy               97s    kubelet                  Readiness probe failed: Get "http://10.240.0.38:8080/healthz": dial tcp 10.240.0.38:8080: connect: connection refused
  Warning  Unhealthy               96s    kubelet                  Liveness probe failed: Get "http://10.240.0.38:8080/healthz": dial tcp 10.240.0.38:8080: connect: connection refused

Not sure how to resolve this. Also, the IP its trying to do HTTP get is not the IP of the hub service

**Comment by rkevin-arch** [comment]
See #139. I need to make a stable release for this.

**Comment by bjornarfjelldal** [comment]
For other stumbling upon this, I am trying to pay it forward by confirming that the latest helm chart referred to in #139 solved this issue for me. Being on Azure, I also needed to set 

```
pvc:
  accessModes:
  - ReadWriteOnce
```

For the pod to start running.

**Comment by TimStewartJ** [comment]
The fix is now contained in the latest stable release. Closing.
