### ISSUE TITLE
Help: endpoint is deprecated

### ISSUE THREAD

**Issue by orboan** [LibreTexts/ngshare#146]
Hello everyone,

I gently request some help to make possible this ngshare service work with jupyterhub >= 2.0. It has been working fine while I used jupyterhub 1.3, but after upgrading jupyterhub to 2.x I get this error:

`/authorizations/cookie endpoint is deprecated in JupyterHub 2.0. Use /api/user with OAuth tokens`

This error appears in the kubectl logs of the jupyterhub pod when I try to access
https://mydomain.com/services/ngshare/

(the browser says “too many redirects”).

Please, any help would be very very appreciated.

Thank you.

**Comment by moorepants** [comment]
Hi everyone, we created this project at UC Davis with a group of CS students for their capstone design project. I then stewarded this with a funded project at UC Davis after that, but now all the students and myself have left the university. I don't think anyone at LibreTexts or UCD is using this anymore, so there are no resources to develop it.

If anyone wants to take over maintenance, I'm happy to give commit rights to the repo and access to pypi and such so you can do so. @rubdos are you interested this?

**Comment by rubdos** [comment]
> If anyone wants to take over maintenance, I'm happy to give commit rights to the repo and access to pypi and such so you can do so. @rubdos are you interested this?

Yeh, sure, I am! Especially if nobody else would be that has more frequent commits than I do.
If you want to contact me in private, I suggest we take my University email at rubedesm at vub dot be

**Comment by rubdos** [comment]
@joernahlers I'm trying to free some time next week to test your pull request on a test cluster and give some feedback if necessary. You're not being forgotten :-)

**Comment by TimStewartJ** [comment]
The new release now takes care of the issue. Thanks to @joernahlers !
