### ISSUE TITLE
Compatibility with nbgrader 0.7.1

### ISSUE THREAD

**Issue by orboan** [LibreTexts/ngshare#147]
Hello,

I am trying to install, in a Dockerfile, this ngshare exchange service, with next:

```
RUN mamba install -c conda-forge --yes \
    jupyter_nbextensions_configurator \
    jupyter_contrib_nbextensions \
    jupyter-server-proxy \
    jupyterlab-drawio \
    nbgrader \
    jupyter-videochat && \
python3 -m pip install ngshare && \
python3 -m pip install ngshare_exchange && \
pip install nbgitpuller && clean-layer.sh

```
But I get this error:

```
#32 190.5 Successfully built ngshare
#32 190.9 Installing collected packages: ngshare
#32 191.0 Successfully installed ngshare-0.5.3
...
#32 191.9 Collecting ngshare_exchange
#32 192.3   Downloading ngshare_exchange-0.5.1.tar.gz (32 kB)
#32 192.4   Preparing metadata (setup.py): started
...
#32 199.7 The conflict is caused by:
#32 199.7     ngshare-exchange 0.5.1 depends on nbgrader==0.7.0.dev0
#32 199.7     ngshare-exchange 0.5.0 depends on nbgrader==0.7.0.dev0
#32 199.7     ngshare-exchange 0.4.0 depends on nbgrader==0.7.0.dev0
#32 199.7     ngshare-exchange 0.3.0 depends on nbgrader==0.7.0.dev0
#32 199.7     ngshare-exchange 0.1.0 depends on nbgrader==0.7.0.dev0
#32 199.7     ngshare-exchange 0.0.1 depends on nbgrader==0.7.0.dev0

```
The nbgrader version installed is [0.7.1](https://github.com/jupyter/nbgrader/releases/tag/v0.7.1).

Why is requiring to be 0.7.0.dev0 and not accepting 0.7.1 nbgrader version? It's strange as in documentation says:

``ngshare_exchange`` only works with nbgrader version 0.7.0 **or above**.

Is there any fix or workaround to this issue (not downgrading nbgrader to 0.7.0.dev0)?

Thank you in advance !

**Comment by orboan** [comment]
I respond myself:

It seems that ngshare_exchange is NOT updated in pip repo, so 

`python3 -m pip install ngshare_exchange`

triggers that error.

But installing it from the github repo as with:

`python3 -m pip install git+https://github.com/LibreTexts/ngshare_exchange.git `

then it works, as dependencies in the repo are updated as nbgrader>=0.7.0

Documentation or pip repo should be updated.

**Comment by TimStewartJ** [comment]
Closing since both the documentation and the pip repo have been updated.
