### ISSUE TITLE
Help:Adding Multiple Students to the Couse Api not accepting the body.

### ISSUE THREAD

**Issue by sravanthipeetla** [LibreTexts/ngshare#148]
Hello,

I tried to hit this api
POST [/api/students/<course_id>](https://test/services/ngshare/): Add multiple students to course
The body which I am trying to send is :
{"students":
    [
        {
            "username": "liustudent01",
            "first_name": "liustudent",
            "last_name": "lastname",
            "email": "liustudent@gmail.com"
        }
    ]
}

Even though I am passing students key to the body.
This give me response:
{
    "success": false,
    "message": "Please supply students"
}
Can anyone please help me with this.

Thank you in advance !

![Screenshot from 2022-09-07 18-48-20](https://user-images.githubusercontent.com/18006444/188888469-389221ff-26ec-42e1-bfdf-6745dab0195b.png)
![Screenshot from 2022-09-07 18-47-43](https://user-images.githubusercontent.com/18006444/188888479-aa3be42e-75c4-4c02-9873-45668b929998.png)

**Comment by lxylxy123456** [comment]
The POST body should be an HTTP form where the key is `student` and value is a JSON array. You are sending a JSON dict where key is `student` and value is a JSON array.
If you use vngshare (see docs), here is the CURL command you should send:
```sh
curl 'http://127.0.0.1:12121/api/students/course2' -X POST --data-raw 'students=%5B%7B%22username%22%3A+%22kevin%22%2C+%22first_name%22%3A+%22kevin_first_name%22%2C+%22last_name%22%3A+%22kevin_last_name%22%2C+%22email%22%3A+%22kevin_email%22%7D%5D&user=abigail'
```
Please ignore the `user=abigail` at the end in actual ngshare. This is how vngshare authenticates.
This is what is sent when viewed by Wireshark:
![image](https://user-images.githubusercontent.com/9337403/189019495-a50b2ba5-4630-4227-bd2d-0505d9b690f5.png)

**Comment by lxylxy123456** [comment]
I see. The documentation (`docs/api/course.rst`) is misleading as it says:
```rst
POST /api/students/<course_id>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*Add or update students. (instructors only)*

If the request syntax is correct, will return 200 and report whether each student is added correctly.

Request (HTTP POST data)
""""""""""""""""""""""""
.. code:: javascript

    {
        "students":
        [
            {
                "username": /* student ID */,
                "first_name": /* student first name */,
                "last_name": /* student last name */,
                "email": /* student email */
            },
            ...
        ]
    }
```

**Comment by sravanthipeetla** [comment]
Thank you for your response.
