### ISSUE TITLE
Request to move the repo to the LibreTexts org

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/ngshare#68]
I think that we should transfer this repo to https://github.com/libretexts before school lets out. This will help keep it in our purview to maintain for the future.

**Comment by lxylxy123456** [comment]
I am fine with it as long as it is still open source. Will you fork this repo or make a new repo and copy the data?

**Comment by moorepants** [comment]
It will be open source and we can keep all you all with push and admin access. My suggestions is to transfer ownership of the repository to the libretexts organization, not to fork or copy it.

**Comment by lxylxy123456** [comment]
I will discuss it with other team members on Wednesday.

**Comment by moorepants** [comment]
That's fine, but keep in mind that most senior design students disappear after graduation never to be heard from again :) I've mentored over 100 teams in the last several years and 0 have maintained projects after graduation. Secondly, Chris and I are the clients, so we're expecting whatever you produce to be "transferred" to us in some sense. I just want to keep the primary repository with us so we have admin rights and full access to what we need to maintain it. If one or more of you plan to maintain this post graduation, let me know so we can factor that into the plans. Moving it to our org wouldn't change anything for your access and admin permissions.

**Comment by lxylxy123456** [comment]
I discussed with other team members and the TA for ECS193 yesterday, and we think we can transfer the repository during week 10 during client sign-off.

**Comment by moorepants** [comment]
FYI, I created a new team on the LibreTexts org and invited all of you. We can transfer there when you are ready.

**Comment by rkevin-arch** [comment]
We just published ngshare and ngshare_exchange version 0.5.1 and verified that Travis is automatically publishing the stable release on the helm repo, PyPI and Dockerhub. Considering how Codecov also works, the transfer is complete and everything works.
